export type CategoryId =
  | "grocery"
  | "coffee"
  | "dining"
  | "transport"
  | "health"
  | "shopping"
  | "treats"
  | "other";

export interface LineItem {
  name: string;
  price: number;
  qty?: number;
  emoji?: string;
}

export interface Receipt {
  id: string;
  merchant: string;
  category: CategoryId;
  date: string; // ISO string
  total: number;
  currency: string; // symbol, e.g. "$"
  items: LineItem[];
  /** short headline nugget shown on the feed card */
  nugget?: string;
  /** User-marked receipt worth keeping close. */
  favorite?: boolean;
  /** When this receipt was saved into Snoopy, used for history ordering. */
  savedAt?: string;
  /**
   * Optional receipt image reference. In the local prototype `imageUrl` can be a
   * compressed data URL; once Blob is wired it should become the private/signed
   * display URL and `imagePath` should hold the Blob pathname.
   */
  imageUrl?: string;
  imagePath?: string;
  imageStoredAt?: string;
  /**
   * Rough total food-energy estimate (kcal) across every edible item, from the
   * vision parse. Undefined when nothing on the receipt is food (fuel, health,
   * shopping) or on mock/sample scans. A playful curiosity, never a judgment.
   */
  calories?: number;
  /**
   * Content-aware reads on THIS receipt, generated by Claude during the vision
   * parse — the specific, curious observations about the actual items. Empty on
   * mock/sample scans (no model in the loop); the reveal falls back to the local
   * pattern engine in that case. See `revealInsights` in lib/insights.ts.
   */
  observations?: Insight[];
  /**
   * Snapshot of the mixed reveal shown when this receipt was saved. Unlike
   * `observations`, this includes local curiosities and history patterns, so
   * history can show the same finds later instead of recomputing a new set.
   */
  revealedInsights?: Insight[];
}

export type InsightTone =
  | "habit"
  | "milestone"
  | "funfact"
  | "savings"
  | "pattern"
  | "cheer"
  | "category"
  // Claude's content-aware read on the receipt itself.
  | "observation";

export interface Insight {
  id: string;
  tone: InsightTone;
  emoji: string;
  title: string;
  body?: string;
}

export interface CategorySlice {
  category: CategoryId;
  total: number;
  count: number;
}

export interface WeeklyReport {
  total: number;
  receiptCount: number;
  headline: string;
  subhead: string;
  slices: CategorySlice[];
  topMerchant?: { merchant: string; count: number; total: number };
  busiestDay?: { label: string; count: number };
  insights: Insight[];
}
